addons:
  firefox: latest
  chrome: stable

env:
  global:
    - TZ=Australia/Canberra

jobs:
  include:
    - name: "Linux"
      language: python
      python: 3.8
    - name: "Windows"
      os: windows
      language: generic
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    
before_install:
  - |
    if [ ${TRAVIS_OS_NAME} == "linux" ]; then
      export TZ=Australia/Canberra;
      DATE=$(date);
    fi
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; then
      export TZ=Australia/Canberra;
      DATE=$(date);
    fi
install:
  - |
    if [ ${TRAVIS_OS_NAME} == "linux" ]; then
    pip install -r requirements.txt
    pip install awscli
    fi
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; then
    choco install -y googlechrome --ignore-checksums
    fi
script:
  - |
    if [ ${TRAVIS_OS_NAME} == "linux" ]; then
    ls -lah;
    echo "The Date is : ${DATE}";
    echo "The Date is : $DATE";
    fi
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; then
    dir /c/Python38/Scripts;
    webdrivermanager firefox chrome --linkpath /c/Python38/Scripts;
    dir /c/Python38/Scripts;
    python ${filename}.py;
    echo "The Date is : ${DATE}";
    echo "The Date is : $DATE";
    fi