addons:
  firefox: latest
  chrome: stable

env:
  global:
    - TZ=Australia/Canberra

jobs:
  include:
    - name: "Linux"
      language: python
      python: 3.8
    - name: "Windows"
      os: windows
      language: shell
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    
before_install:
  - |
    if [ ${TRAVIS_OS_NAME} == "linux" ]; then
      export TZ=Australia/Canberra;
      DATE=$(date);
    fi
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; then
      export TZ=Australia/Canberra;
      DATE=$(date);
      choco install googlechrome
      choco install python --version 3.8.0;
      python --version;
      python -m pip install --upgrade pip;
    fi
install:
  - pip install -r requirements.txt
  - pip install awscli
script:
  - |
    if [ ${TRAVIS_OS_NAME} == "linux" ]; then
    ls -lah;
    echo "The Date is : ${DATE}";
    echo "The Date is : $DATE";
    fi
  - |
    if [ ${TRAVIS_OS_NAME} == "windows" ]; then
    dir /c/Python38/Scripts;
    webdrivermanager firefox chrome --linkpath /c/Python38/Scripts;
    dir /c/Python38/Scripts;
    python ${filename}.py;
    echo "The Date is : ${DATE}";
    echo "The Date is : $DATE";
    fi

# - name: "Python 3.8.0 on Windows"
#   os: windows           # Windows 10.0.17134 N/A Build 17134
#   language: shell       # 'language: python' is an error on Travis CI Windows
#   addons:
#     firefox: latest
#     chrome: stable
#   before_install:
#     - choco install python --version 3.8.0
#     - python --version
#     - python -m pip install --upgrade pip
#   env: PATH=/c/Python38:/c/Python38/Scripts:$PATH=
#   install:
#     - pip install -r requirements.txt
#     - pip install awscli
#   script:
#     - dir /c/Python38/Scripts
#     - webdrivermanager firefox chrome --linkpath /c/Python38/Scripts
#     - dir /c/Python38/Scripts
#     - python ${filename}.py
#     - echo %date:~7,2%-%date:~4,2%-%date:~10,4%
    