language: 
  - python            # this works for Linux but is an error on macOS or Windows
  - shell
python:
- '3.9'
addons:
  firefox: latest
  chrome: stable
os:
- linux
- windows
matrix:
  include:    
    before_install:
      - os: linux
        - export TZ=Australia/Canberra
        - DATE=$(date +%Y-%m-%d)
      - os: windows
        - choco install python --version 3.8.0
        - python --version
        - python -m pip install --upgrade pip
    install:
      - pip install -r requirements.txt
      - pip install awscli
    script:
      - os: linux
        - ls -lah
      - os: windows
        - dir /c/Python38/Scripts
        - webdrivermanager firefox chrome --linkpath /c/Python38/Scripts
        - dir /c/Python38/Scripts
        - python ${filename}.py
        - echo %date:~7,2%-%date:~4,2%-%date:~10,4%
  
    # - name: "Python 3.8.0 on Windows"
    #   os: windows           # Windows 10.0.17134 N/A Build 17134
    #   language: shell       # 'language: python' is an error on Travis CI Windows
    #   addons:
    #     firefox: latest
    #     chrome: stable
    #   before_install:
    #     - choco install python --version 3.8.0
    #     - python --version
    #     - python -m pip install --upgrade pip
    #   env: PATH=/c/Python38:/c/Python38/Scripts:$PATH=
    #   install:
    #     - pip install -r requirements.txt
    #     - pip install awscli
    #   script:
    #     - dir /c/Python38/Scripts
    #     - webdrivermanager firefox chrome --linkpath /c/Python38/Scripts
    #     - dir /c/Python38/Scripts
    #     - python ${filename}.py
    #     - echo %date:~7,2%-%date:~4,2%-%date:~10,4%
        